# Generated by Django 2.0 on 2017-12-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='deposit_account',
            name='on_hold',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='deposit_account',
            name='over_draft',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
