# Generated by Django 2.0 on 2017-12-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171218_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
    ]
