# Generated by Django 2.0 on 2017-12-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171218_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_account', to='app.customer'),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account', to='app.customer'),
        ),
    ]
